services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    restart: always
    volumes:
      - wp_data:/wordpress
    networks:
      - services

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file: .env
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - services

  wordpress:
    container_name: wp
    build: ./requirements/wordpress/
    restart: always
    env_file: .env
    volumes:
      - wp_data:/wordpress
    networks:
      - services
      - cache-wp

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    env_file: .env
    networks:
      - cache-wp

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    networks:
      - services

  sftp:
    container_name: sftp
    build: ./requirements/bonus/sftp
    env_file: .env
    restart: always
    ports:
      - 2222:22
    volumes:
      - wp_data:/home/${SFTP_USER}/wordpress
    networks:
      - services

  cockpit:
    container_name: cockpit
    build: ./requirements/bonus/cockpit
    env_file: .env
    restart: always
    networks:
      - services
    privileged: true
    ports:
      - 9090:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_GID=108
   
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - services
      
networks:
  services:
  cache-wp:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sameidu/data/mariadb_data
      o: bind

  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sameidu/data/wp_data
      o: bind

